[package]
name = "atcoder-judger"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
reqwest = { version = "0.12.9", features = ["blocking"] }
scraper = "0.21.0"
